routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
    |----------Frontend Login Route Start----------|
*/
    Route::get('/frontendlogin', 'Frontend\LoginController@showLoginForm');
    Route::post('/frontendlogin', 'Frontend\LoginController@login')->name('frontendlogin');
    Route::post('/frontendlogout', 'Frontend\LoginController@logout')->name('frontendlogout');
/*
    |----------Frontend Login Route Start----------|
 */
/*-----------------Portfolio Route Start-----------------*/
    Route::get('/portfolio/{slug}', 'Frontend\frontendController@home');
    /*Route::get('/about-us', 'Frontend\frontendController@about');
    Route::get('/services', 'Frontend\frontendController@services');
    Route::get('/team', 'Frontend\frontendController@team');
    Route::get('/contact-us', 'Frontend\frontendController@contactUs');*/
/*-----------------Portfolio Route End-----------------*/

Route::get('/', 'Frontend\frontendController@index');
Route::get('/post/{id}', 'Frontend\frontendController@postDetail')->name('postdetail');
Route::get('/comment', 'Admin\CommentController@index')->name('comment.index');
Route::post('/comment/', 'Admin\CommentController@store')->name('comment.store');
Route::get('/comment/edit/{id}', 'Admin\CommentController@edit')->name('comments.edit');
Route::put('/{id}', 'Admin\CommentController@update')->name('comments.update');
Route::delete('/delete/{id}', 'Admin\CommentController@destroy')->name('comments.delete');



Route::prefix('users')->name('user.')->group(function () {
	Route::get('/', 'Admin\UsersController@index')->name('index');
    Route::get('/add', 'Admin\UsersController@create')->name('create');
    Route::post('/', 'Admin\UsersController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('edit');
    Route::put('/{id}', 'Admin\UsersController@update')->name('update');
    Route::get('/view/{id}', 'Admin\UsersController@show')->name('view');
    Route::delete('/delete/{id}','Admin\UsersController@destroy')->name('delete');
});

Route::prefix('posts')->name('posts.')->group(function () {
    Route::get('/', 'Admin\PostController@index')->name('index');
    Route::get('/addpost', 'Admin\PostController@create')->name('create');
    Route::post('/', 'Admin\PostController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\PostController@edit')->name('edit');
    Route::put('/{id}', 'Admin\PostController@update')->name('update');
    Route::get('/view/{id}', 'Admin\PostController@show')->name('view');
    Route::delete('/delete/{id}','Admin\PostController@destroy')->name('delete');

        Route::prefix('image')->name('image.')->group(function () {
            Route::get('/{id}', 'Admin\ImageController@index')->name('listing');
            Route::post('/{id}', 'Admin\ImageController@store')->name('save');
            Route::delete('/delete/{id}', 'Admin\ImageController@destroy')->name('delete');
            Route::get('/edit/{id}', 'Admin\ImageController@edit')->name('edit');
            Route::put('/{id}', 'Admin\ImageController@update')->name('update');
        });
});
Route::prefix('pages')->name('pages.')->group(function (){
    Route::get('/', 'Admin\PagesController@index')->name('index');
    Route::get('/create', 'Admin\PagesController@create')->name('create');
    Route::post('/', 'Admin\PagesController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\PagesController@edit')->name('edit');
    Route::put('/{id}', 'Admin\PagesController@update')->name('update');
    Route::get('/view{id}', 'Admin\PagesController@show')->name('view');
    Route::delete('/delete/{id}','Admin\PagesController@destroy')->name('delete');
});

Route::prefix('menus')->name('menus.')->group(function (){
    Route::get('/', 'Admin\MenuController@index')->name('index');
    Route::get('/create', 'Admin\MenuController@create')->name('create');
    Route::post('/', 'Admin\MenuController@store')->name('store');
    Route::get('edit/{id}', 'Admin\MenuController@edit')->name('edit');
    Route::put('/{id}', 'Admin\MenuController@update')->name('update');
    Route::delete('/delete/{id}', 'Admin\MenuController@destroy')->name('delete');
    /*Route::get('/', 'Admin\SubmenuController@index')->name('index');
    Route::get('/create', 'Admin\SubmenuController@create')->name('create');
    Route::post('/', 'Admin\SubmenuController@store')->name('store');
    Route::get('edit/{id}', 'Admin\SubmenuController@edit')->name('edit');
    Route::put('/{id}', 'Admin\SubmenuController@update')->name('update');
    Route::delete('/delete/{id}', 'Admin\SubmenuController@destroy')->name('delete');*/
});     


Route::get('/login', 'Admin\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Admin\LoginController@login');
Route::post('/logout', 'Admin\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index');
});

Route::get('/password/reset', 'Admin\ForgotPasswordController@showForm')->name('password.request');
Route::post('password/email', 'Admin\ForgotPasswordController@sendEmail')->name('password.email');
Route::get('password/reset/{token}', 'Admin\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Admin\ResetPasswordController@resetPassword')->name('password.update');

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class Menu extends Model
{
    protected $guarded = [];
    
    use NodeTrait;

    public function getLftName()
    {
        return 'left';
    }

    public function getRgtName()
    {
        return 'right';
    }

    public function getParentIdName()
    {
        return 'parent_id';
    }

	public function page()
    {
        return $this->hasOne('App\Page', 'id', 'ref_value');
    }
}

app/Http/Controllers/Admin/MenuController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MenuStoreRequest;
use App\Repositories\MenuRepository;
use App\Page;
use App\Menu;


class MenuController extends Controller
{
	protected $menuRepository;
	/**
	 * summary
	 */
	public function __construct(MenuRepository $menus)
	{
	   $this->menuRepository = $menus;
	}
    /**
	* 
	* Display a listing of the Pages.
	*
	*/
	public function index()
	{
		$menus = $this->menuRepository->get();
		return view('admin.menus.list', [
			'menus' => $menus
		]);
	}

    /**
	* 
	* Show Form For Create Menu.
	*
	*/
	public function create()
	{
		$pages = Page::get();
		$menus = Menu::get()->toTree();
		return view('admin.menus.create',compact('pages','menus'));
	}

    /**
	* 
	* Store menus to Storage.
	*
	*/
	public function store(MenuStoreRequest $request)
	{
		$this->menuRepository->store($request);
		return redirect()->route('menus.index')->with('message', 'Menu Created Successfully');
	}

    /**
	* 
	* Show Form For Editing Specific Menu.
	*
	*/
	public function edit($id)
	{
		$pages = Page::get();
		$menus = Menu::get()->toTree();
		$menu = $this->menuRepository->edit($id);
		return view('admin.menus.edit', compact('menu','pages','menus'));
	}

    /**
	* 
	* Update Specific Menu.
	*
	*/
	public function update(MenuStoreRequest $request, $id)
	{
		$this->menuRepository->update($request, $id);
		return redirect()->route('menus.index')->with('message', 'Menu Updated Successfully');
	}

    /**
	* 
	* Update Specific Menu.
	*
	*/
	public function destroy($id)
	{
		$this->menuRepository->delete($id);
		return redirect()->route('menus.index')->with('message', 'Menu Deleted Successfully');
			
	}
}

resources/views/admin/menus/create.blade.php
@extends('../admin.layout.master')
@section('title', 'Create Menu')
@section('content')

	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
			<div class="card mt-4">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4 class="text-info">
						Create Menu
					</h4>
				</div>
				<div class="card-body">
		    		<div class="container">
		    			<div class="row">
		    				<div class="col-xl-12">
		    					<div class="form_area">
		    					    <form action="{{ route('menus.store') }}" method="POST" enctype="multipart/form-data">
		    					        {{ csrf_field() }}
		    					        @include('admin.menus.form')
		    					    </form>
		    					</div>
		    				</div>
		    			</div>
		    		</div>
				</div>
			</div>
	</section>

@endsection

resources/views/admin/menus/edit.blade.php
@extends('../admin.layout.master')
@section('title', 'Edit Menu')
@section('content')

	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
			<div class="card mt-4">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4 class="text-info">Edit Menu</h4>
				</div>
				<div class="card-body">
		    		<div class="container">
		    			<div class="row">
		    				<div class="col-xl-12">
		    					<div class="form_area">
		    					    <form action="{{ route('menus.update', ['id' => $menu->id]) }}" method="POST" enctype="multipart/form-data">
                                        {{method_field('PUT')}}
		    					    	{{ csrf_field() }}
		    					    	@include('admin.menus.form')
    	    					    </form>
		    					</div>
		    				</div>
		    			</div>
		    		</div>
				</div>
			</div>
	</section>

@endsection

resources/views/admin/menus/form.blade.php
<div class="row">
	<div class="col-xl-12">
		<div class="form-group">
			<label>Menu:</label>
			<select name="parent_id" class="form-control">
				<option value="">Select Parent Menu</option>
				@if(isset($menu))
					@php
						$traverse = function ($menus, $prefix = '-') use (&$traverse, $menu) {
							foreach ($menus as $menuItem) {
						    	$select = ($menuItem->id == $menu->parent_id) ? 'selected': '';
					        	echo '<option value="'.$menuItem->id.'" '.$select.' >'.$prefix.' '.$menuItem->name.'</option>';
						        $traverse($menuItem->children, $prefix.'-');
						    }
						};
						$traverse($menus, '');
					@endphp
				@else
					@php
						$traverse = function ($menus, $prefix = '-') use (&$traverse) {
						    foreach ($menus as $menu) {
						        echo '<option value="'.$menu->id.'">'.$prefix.' '.$menu->name.'</option>';
						        $traverse($menu->children, $prefix.'-');
						    }
						};
						$traverse($menus, '');
					@endphp
				@endif
			</select>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xl-12">
		<div class="form-group">
		    <label>Sub Menu:</label>
		    <input type="text" class="form-control" name="name" 
		    value="@if(isset($menu->name)){{ $menu->name }}@else{{ old('name') }}@endif">
		    @error('name')
		        <div class="text-danger">{{ $message }}</div>
		    @enderror
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xl-12">
		<div class="form-group">
		    <label>Menu Type:</label>
		    @if(isset($menu))
		    	<input type="radio" name="menu_type" class="mr-1 ml-2" onclick="show_page();" value="Page"  @if($menu->ref_type == 'Page') {{ 'checked' }}@endif >Page
		    	<input type="radio" name="menu_type" class="mr-1 ml-2" onclick="show_url();" value="Url"  @if($menu->ref_type == 'Url') {{ 'checked' }}@endif >URL
		        <div class="row">
					<div class="col-xl-6 offset-xl-1">
		                <div class="page hide" id="page">
							<label>Page</label>
							<select class="form-control" name="page">
								<option value="">Select The Page</option>
								@foreach($pages as $page)
									<option value="{{$page->id}}"
										@if($page->id == $menu->ref_value)
											{{'selected'}}
										@endif
										>{{$page->name}}</option>
								@endforeach
							</select>
		                </div>
					</div>
		        </div>
		        <div class="row">
					<div class="col-xl-6 offset-xl-1">
		                <div class="url hide" id="url">
							<label class="d-flex align-items-center">
								URL:
								<input type="text" name="url" class="form-control ml-2" 
								@if($menu->ref_type == 'Url')
									value="{{$menu->ref_value}}" 
								@else
									value="" 
								@endif
								>
							</label>
						</div>
					</div>
		        </div>
		    @else
		    	<input type="radio" name="menu_type" class="mr-1 ml-2" onclick="show_page();" value="Page">Page
		    	<input type="radio" name="menu_type" class="mr-1 ml-2" onclick="show_url();" value="Url">URL
		        <div class="row">
					<div class="col-xl-6 offset-xl-1">
		                <div class="page hide" id="page">
							<label>Page</label>
							<select class="form-control" name="page">
								<option value="">Select The Page</option>
								@foreach($pages as $page)
									<option value="{{$page->id}}">
										{{$page->name}}
									</option>
								@endforeach
							</select>
		                </div>
					</div>
		        </div>
		        <div class="row">
					<div class="col-xl-6 offset-xl-1">
		                <div class="url hide" id="url">
							<label class="d-flex align-items-center">
								URL:
								<input type="text" name="url" class="form-control ml-2">
							</label>
						</div>
					</div>
		        </div>
		    @endif
		    @error('menu_type')
		        <div class="text-danger">{{ $message }}</div>
		    @enderror
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xl-12">
		<div class="form-group">
		    <label>Display Order:</label>
		    <input type="text" class="form-control" name="order" 
		    value="@if(isset($menu->display_order)){{ $menu->display_order }}@else{{ old('order') }}@endif">
		</div>
		@error('order')
		    <div class="text-danger">{{ $message }}</div>
		@enderror
	</div>
</div>
<div class="row">
	<div class="col-xl-12">
		<div class="form-group">
			<label class="text-muted d-flex align-items-center">
				Status:
				<input type="hidden" name="status" class="mr-1 ml-2" value="0">
				<input type="checkbox" name="status" class="mr-1 ml-2" value="1"
					@if(isset($menu->status))
					    {{'checked'}}
					@endif
				>Published
			</label>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-xl-12">
		<div class="form-group">
		    <input type="submit" class="btn btn-info" name="submit" value="Save">
		    <a href="{{ route('menus.index') }}" class="btn btn-success">Back</a>
		</div>
	</div>
</div>

resources/views/admin/menus/list.blade.php
@extends('../admin.layout.master')
@section('title', 'Menus List')
@section('content')

	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
			<div class="card mt-4">
				<div class="card-header d-flex justify-content-between align-items-center">
					<h4 class="text-info">Menu Listing</h4>
					<a href="{{ route('menus.create') }}" class="btn btn-info">Create Menu</a>
				</div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>Id</th>
									<th>Name</th>
									<th>Status</th>
									<th>Order</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@foreach($menus as $menu)
									<tr>
										<td>{{$menu->id}}</td>
										<td>{{$menu->name}}</td>
										<td>
											@if($menu->status == 1)
												{{'Published'}}
											@else
												{{'Unpublished'}}
											@endif
										</td>
										<td>{{$menu->display_order}}</td>
										<td>
											<a href="{{ route('menus.edit', ['id' => $menu->id]) }}" class="btn btn-info">
												<i class="fa fa-pencil"></i>
											</a>
											<form method="POST" action="{{ route('menus.delete', ['id' => $menu->id]) }}" style="margin-right: 5px;">
											    {{ csrf_field() }}
											    {{ method_field('DELETE') }}
											    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></button>
											</form>
										</td>
										</tr>
								@endforeach	
							</tbody>
						</table> 
						{{-- $menus->links() --}}
					</div>
				</div>
			</div>
		</div>
	</section>
@endsection