routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
    |----------Frontend Login Route Start----------|
*/
    Route::get('/frontendlogin', 'Frontend\LoginController@showLoginForm');
    Route::post('/frontendlogin', 'Frontend\LoginController@login')->name('frontendlogin');
    Route::post('/frontendlogout', 'Frontend\LoginController@logout')->name('frontendlogout');
/*
    |----------Frontend Login Route Start----------|
 */
/*-----------------Portfolio Route Start-----------------*/
    Route::get('/portfolio/{slug}', 'Frontend\frontendController@home');
    /*Route::get('/about-us', 'Frontend\frontendController@about');
    Route::get('/services', 'Frontend\frontendController@services');
    Route::get('/team', 'Frontend\frontendController@team');
    Route::get('/contact-us', 'Frontend\frontendController@contactUs');*/
/*-----------------Portfolio Route End-----------------*/

Route::get('/', 'Frontend\frontendController@index');
Route::get('/post/{id}', 'Frontend\frontendController@postDetail')->name('postdetail');
Route::get('/comment', 'Admin\CommentController@index')->name('comment.index');
Route::post('/comment/', 'Admin\CommentController@store')->name('comment.store');
Route::get('/comment/edit/{id}', 'Admin\CommentController@edit')->name('comments.edit');
Route::put('/{id}', 'Admin\CommentController@update')->name('comments.update');
Route::delete('/delete/{id}', 'Admin\CommentController@destroy')->name('comments.delete');



Route::prefix('users')->name('user.')->group(function () {
	Route::get('/', 'Admin\UsersController@index')->name('index');
    Route::get('/add', 'Admin\UsersController@create')->name('create');
    Route::post('/', 'Admin\UsersController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('edit');
    Route::put('/{id}', 'Admin\UsersController@update')->name('update');
    Route::get('/view/{id}', 'Admin\UsersController@show')->name('view');
    Route::delete('/delete/{id}','Admin\UsersController@destroy')->name('delete');
});

Route::prefix('posts')->name('posts.')->group(function () {
    Route::get('/', 'Admin\PostController@index')->name('index');
    Route::get('/addpost', 'Admin\PostController@create')->name('create');
    Route::post('/', 'Admin\PostController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\PostController@edit')->name('edit');
    Route::put('/{id}', 'Admin\PostController@update')->name('update');
    Route::get('/view/{id}', 'Admin\PostController@show')->name('view');
    Route::delete('/delete/{id}','Admin\PostController@destroy')->name('delete');

        Route::prefix('image')->name('image.')->group(function () {
            Route::get('/{id}', 'Admin\ImageController@index')->name('listing');
            Route::post('/{id}', 'Admin\ImageController@store')->name('save');
            Route::delete('/delete/{id}', 'Admin\ImageController@destroy')->name('delete');
            Route::get('/edit/{id}', 'Admin\ImageController@edit')->name('edit');
            Route::put('/{id}', 'Admin\ImageController@update')->name('update');
        });
});
Route::prefix('pages')->name('pages.')->group(function (){
    Route::get('/', 'Admin\PagesController@index')->name('index');
    Route::get('/create', 'Admin\PagesController@create')->name('create');
    Route::post('/', 'Admin\PagesController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\PagesController@edit')->name('edit');
    Route::put('/{id}', 'Admin\PagesController@update')->name('update');
    Route::get('/view{id}', 'Admin\PagesController@show')->name('view');
    Route::delete('/delete/{id}','Admin\PagesController@destroy')->name('delete');
});

Route::prefix('menus')->name('menus.')->group(function (){
    Route::get('/', 'Admin\MenuController@index')->name('index');
    Route::get('/create', 'Admin\MenuController@create')->name('create');
    Route::post('/', 'Admin\MenuController@store')->name('store');
    Route::get('edit/{id}', 'Admin\MenuController@edit')->name('edit');
    Route::put('/{id}', 'Admin\MenuController@update')->name('update');
    Route::delete('/delete/{id}', 'Admin\MenuController@destroy')->name('delete');
    /*Route::get('/', 'Admin\SubmenuController@index')->name('index');
    Route::get('/create', 'Admin\SubmenuController@create')->name('create');
    Route::post('/', 'Admin\SubmenuController@store')->name('store');
    Route::get('edit/{id}', 'Admin\SubmenuController@edit')->name('edit');
    Route::put('/{id}', 'Admin\SubmenuController@update')->name('update');
    Route::delete('/delete/{id}', 'Admin\SubmenuController@destroy')->name('delete');*/
});     


Route::get('/login', 'Admin\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Admin\LoginController@login');
Route::post('/logout', 'Admin\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index');
});

Route::get('/password/reset', 'Admin\ForgotPasswordController@showForm')->name('password.request');
Route::post('password/email', 'Admin\ForgotPasswordController@sendEmail')->name('password.email');
Route::get('password/reset/{token}', 'Admin\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Admin\ResetPasswordController@resetPassword')->name('password.update');

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;
use App\Notifications\CustomResetPasswordNotification;

class User extends Authenticatable
{
    use Sortable;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public $sortable = [
        'id', 'name', 'email',
    ];
    
    /**
     * Send the password reset notification.
     *
     * @param  string  $token
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new CustomResetPasswordNotification($token));
    }

    public function posts()
    {
        return $this->hasMany('App\Post');
    }

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public static function boot() 
    {
        parent::boot();

        static::deleting(function($user) {
            // before delete() method call this
            $user->posts()->delete();
            $user->comments()->delete();
        });
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserStoreRequest;
use App\Repositories\UserRepository;


class UsersController extends Controller
{
    protected $usersRepository;

    public function __construct(UserRepository $users)
    {
        $this->usersRepository = $users;
    }

    /**
     * Display a listing of the Users.
     *
     * @return \Illuminate\Http\Response
     */

    public function index(Request $request)
    {
        $users = $this->usersRepository->paginate($request);
        return view('admin.users.user',[
            'users'=>$users
        ]);
    }

    /**
     * Show the form for creating a new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.createuser');
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserStoreRequest $request)
    {
        $this->usersRepository->store($request);
        return redirect()->route('user.index')->with('message', 'User Registered successfully');
    }

    /**
     * Display the specified User.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user_detail = $this->usersRepository->show($id);
        return view('admin.users.userdetail',[
            'user'=>$user_detail
        ]);
    }

    /**
     * Show the form for editing the specified User.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user_editing = $this->usersRepository->edit($id);
        return view('admin.users.edit',[
            'user'=>$user_editing
        ]);
    }

    /**
     * Update the specified User in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserStoreRequest $request, $id)
    {
        $this->usersRepository->update($id, $request);
        return redirect()->route('user.index')->with('message', 'User Updated successfully');
    }

    /**
     * Remove the specified User from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->usersRepository->delete($id);
        return redirect()->route('user.index')->with('message', 'User deleted successfully');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Image;
use DB;
use App\Registration;

class UserController extends Controller
{
    
    public function index(){
	    $users = DB::select('select * from registrations');
	    return view('userlist',['users'=>$users]);
    }

    public function store(Request $request)
    {
    	/*$this->validate($request,[
			'name'=>'required|min:5',
			'email'=>'required|email',
			'password'=>'required',
      	]);*/
      	$name = $request->name;
      	$email = $request->email;
      	$password = $request->password;
        if ($request->hasFile('image')) {
            $image = $request->image;
            //image name with Extension
            $filenamewithextension = $image->getClientOriginalName();
            //image name without Extension
            $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);
            //get file extension
            $extension = $image->getClientOriginalExtension();
            //filename to store
            $filenametostore = $filename.'_'.uniqid().'.'.$extension;
            
            Storage::put('public/images/'. $filenametostore, fopen($image, 'r+'));
            Storage::put('public/images/thumbnail/'. $filenametostore, fopen($image, 'r+'));
            $thumbnailpath = public_path('storage/images/thumbnail/'.$filenametostore);
            $img = Image::make($thumbnailpath)->resize(100, 100)->save($thumbnailpath);
        }
        $data=array('name'=>$name,"email"=>$email,"password"=>$password,"image"=>$filenametostore);
	    DB::table('registrations')->insert($data);
	    //return redirect()->back()->with('message', 'User Registered successfully');
        //return redirect()->route('view-records');
        return redirect()->action('UserController@index')->with('message', 'User Registered successfully');
    }

    public function show($id){
        $user = Registration::find($id);
    	return view('edit',[
            'user'=>$user
        ]);
    }

    public function update(Request $request){
    	$id = $request->hidden_id;
    	$name = $request->name;
    	$email = $request->email;
    	$password = $request->password;
        $image = $request->image;
        if ($image=="") {
            $users = DB::select('select image from registrations where id = ?',[$id]);
            $image = $users[0]->image;
            DB::update('update registrations set name = ?, email = ?, password = ?, image = ? where id = ?',[$name,$email,$password,$image,$id]);
            return redirect()->action('UserController@index')->with('message', 'User Updated successfully');  
        }else{
            if ($request->hasFile('image')) {
                $image = $request->image;
                //image name with Extension
                $filenamewithextension = $image->getClientOriginalName();
                //image name without Extension
                $filename = pathinfo($filenamewithextension, PATHINFO_FILENAME);
                //get file extension
                $extension = $image->getClientOriginalExtension();
                //filename to store
                $filenametostore = $filename.'_'.uniqid().'.'.$extension;
                Storage::put('public/images/'. $filenametostore, fopen($image, 'r+'));
                Storage::put('public/images/thumbnail/'. $filenametostore, fopen($image, 'r+'));
                $thumbnailpath = public_path('storage/images/thumbnail/'.$filenametostore);
                $img = Image::make($thumbnailpath)->resize(100, 100)->save($thumbnailpath);
                DB::update('update registrations set name = ?, email = ?, password = ?, image = ? where id = ?',[$name,$email,$password,$filenametostore,$id]);
                return redirect()->action('UserController@index')->with('message', 'User Updated successfully');
            }
        }
    }
    public function delete($id){
        $users = DB::select('select image from registrations where id = ?',[$id]);
        $image = $users[0]->image;
        if(Storage::exists('public/images/'.$image) && Storage::exists('public/images/thumbnail/'.$image)) {
            if(Storage::delete('public/images/'.$image) && Storage::delete('public/images/thumbnail/'.$image)){
                DB::delete('delete from registrations where id = ?',[$id]);
                return redirect()->back()->with('message', 'User Deleted successfully');
            }else{
                dd('no');
            }
        } else {
            dd('no');
        }
    	
    }
}

resources/views/admin/users/createuser.blade.php
@extends('../admin.layout.master')
@section('title', 'Add User')
@section('content')
	<section class="header_section">
	    <div class="container">
	        <div class="row">
	            <div class="col-xl-12">
					<div class="card">
						<div class="card-header">
							<h3 class="text-info">
							    Add User
							</h3>
						</div>
						<div class="card-body">
							<div class="container">
								<div class="row">
									<div class="col-xl-12">
										<div class="form_area">
										    <form action="{{ route('user.store')}}" method="POST" enctype="multipart/form-data">
										        {{ csrf_field() }}
										        <div class="row">
										        	<div class="col-xl-4">
											            <div class="form-group">
											                <label class="text-muted">Name:</label>
											                <input type="text" class="form-control" name="name" value="{{ old('name') }}">
											                @error('name')
											                    <div class="text-danger">{{ $message }}</div>
											                @enderror
											            </div>
										        	</div>
										        </div>
										        <div class="row">
										        	<div class="col-xl-4">
											            <div class="form-group">
											                <label class="text-muted">Email:</label>
											                <input type="email" class="form-control" name="email">
											                @error('email')
											                    <div class="text-danger">{{ $message }}</div>
											                @enderror
											            </div>
										        	</div>
										        </div>
										        <div class="row">
										        	<div class="col-xl-4">
											            <div class="form-group">
											                <label class="text-muted">password:</label>
											                <input type="password" class="form-control" name="password">
											                @error('password')
											                    <div class="text-danger">{{ $message }}</div>
											                @enderror
											            </div>
										        	</div>
										        </div>
										        <div class="row">
										        	<div class="col-xl-4">
											            <div class="form-group">
											            	<label class="text-muted d-flex align-items-center">
											            		Status:
											            		<input type="radio" name="status" class="mr-1 ml-2" value="1" @if(old('status')=='1')) checked @endif>Active
											            		<input type="radio" name="status" class="mr-1 ml-2" value="0" @if(old('status')=='0')) checked @endif>Deactive
															</label>
											                @error('status')
											                    <div class="text-danger">{{ $message }}</div>
											                @enderror
											            </div>
										        	</div>
										        </div>
										        <div class="row">
										        	<div class="col-xl-4">
											            <div class="form-group">
											                <label class="text-muted">Image:</label>
											                <input type="file" class="form-control" name="image">
											                @error('image')
											                    <div class="text-danger">{{ $message }}</div>
											                @enderror
											            </div>
										        	</div>
										        </div>
										        <div class="row">
										        	<div class="col-xl-4">
											            <div class="form-group">
											                <input type="submit" class="btn btn-info" name="submit" value="Add">
											                <a href="{{ route('user.index')}}" class="btn btn-success">Back</a>
											            </div>
											        </div>
										        </div>
										    </form>
										</div>
									</div>
								</div>
							</div>		
						</div>
					</div>
	            </div>
	        </div>
	    </div>
	</section>
	<!--<section class="form_section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					<div class="form_area">
					    <form action="{{-- route('user.store')}}" method="POST" enctype="multipart/form-data">
					        {{ csrf_field() }}
					        <div class="row">
					            <div class="form-group">
					                <label>Name:</label>
					                <input type="text" class="form-control" name="name">
					                @error('name')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Email:</label>
					                <input type="email" class="form-control" name="email">
					                @error('email')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>password:</label>
					                <input type="password" class="form-control" name="password">
					                @error('password')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Status:</label>
					                <select class="form-control" name="status">
					                	<option>Select the status</option>
					                	<option value="1">Active</option>
					                	<option value="0">Deactive</option>
					                </select>
					                @error('status')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Image:</label>
					                <input type="file" class="form-control" name="image">
					                @error('image')
					                    <div class="text-danger">{{ $message }}</div>
					                @enderror
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <input type="submit" class="btn btn-info" name="submit" value="Add">
					                <a href="{{ route('user.index')--}}" class="btn btn-success">Back</a>
					            </div>
					        </div>
					    </form>
					</div>
				</div>
			</div>
		</div>
	</section>-->
@endsection

resources/views/admin/users/edit.blade.php
@extends('../admin.layout.master')
@section('title', 'User Update')
@section('content')
	<section class="header_section">
	    <div class="container">
	        <div class="row">
	            <div class="col-xl-12">
					<div class="card">
						<div class="card-header">
							<h3 class="text-info">
							    Update User
							</h3 class="text-info">
						</div>
						<div class="card-body">
							<div class="container">
								<div class="row">
									<div class="col-xl-12">
										<div class="form_area">
										    <form action="{{ route('user.update', ['id' => $user->id]) }}" method="POST" enctype="multipart/form-data">
										    	{{method_field('PUT')}}
										        {{ csrf_field() }}
										        <div class="row">
										            <div class="col-xl-6">
											            <div class="form-group">
											                <label class="text-Muted">Name:</label>
											                <input type="text" class="form-control" name="name" value="{{$user->name}}">
											                @error('name')
											                    <div class="text-danger">{{ $message }}</div>
											                @enderror
											            </div>
											        </div>
										        </div>
										        <div class="row">
										            <div class="col-xl-6">
											            <div class="form-group">
											                <label class="text-Muted">Email:</label>
											                <input type="email" class="form-control" name="email" value="{{$user->email}}">
											                @error('email')
											                    <div class="text-danger">{{ $message }}</div>
											                @enderror
											            </div>
											        </div>
										        </div>
										        <div class="row">
										            <div class="col-xl-6">
											            <div class="form-group">
							            	            	<label class="text-muted d-flex align-items-center">
							            	            		Status:
							            	            		<input type="Radio" name="status" class="mr-1 ml-2" value="1" 
						            	            				@if($user->status == 1)
																		{{'checked'}}
								            	            		@endif
							            	            		>Active
							            	            		<input type="Radio" name="status" class="mr-1 ml-2" value="0"
						            	            				@if($user->status == 0)
																		{{'checked'}}
								            	            		@endif
							            	            		>Deactive
							            					</label>
							            					@error('status')
							            					    <div class="text-danger">{{ $message }}</div>
							            					@enderror
											            </div>
											        </div>    
										        </div>
										        <div class="row">
										            <div class="col-xl-6">
											            <div class="form-group">
											                <label class="text-Muted">Image:</label>
											                <input type="file" class="form-control" name="image">
											                <img src="{{ asset('images/').'/'.$user->image}}" alt="..." height="50" width="50" class="mt-2" />
											            </div>
											        </div>    
										        </div>
										        <div class="row">
										            <div class="col-xl-6">
											            <div class="form-group">
											                <input type="submit" class="btn btn-info" name="submit" value="Update">
											                <a href="{{ route('user.index')}}" class="btn btn-success">Back</a>
											            </div>
											        </div>
										        </div>
										    </form>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
	            </div>
	        </div>
	    </div>
	</section>
	<!--<section class="form_section">
		<div class="container">
			<div class="row">
				<div class="col-xl-12">
					<div class="form_area">
					    <form action="{{ route('user.update', ['id' => $user->id]) }}" method="POST" enctype="multipart/form-data">
					    	{{method_field('PUT')}}
					        {{ csrf_field() }}
					        <div class="row">
					            <div class="form-group">
					                <label>Name:</label>
					                <input type="text" class="form-control" name="name" value="{{$user->name}}">
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Email:</label>
					                <input type="email" class="form-control" name="email" value="{{$user->email}}">
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Status:</label>
					                <select class="form-control" name="status">
					                	@php
					                		$value = $user->status;
					                	@endphp
					                	<option value="1"
					                		@php
					                			if($value == 1){
					                				echo 'selected';
					                			}
											@endphp
					                	>Active</option>
					                	<option value="0"
            		                		@php 
            		                			if($value == 0){
            		                				echo 'selected';
            		                			}
            								@endphp
					                	>Deactive</option>
					                </select>
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <label>Image:</label>
					                <input type="file" class="form-control" name="image">
					                <img src="{{ asset('storage/images/').'/'.$user->image}}" alt="..." height="50" width="50" />
					            </div>
					        </div>
					        <div class="row">
					            <div class="form-group">
					                <input type="submit" class="btn btn-info" name="submit" value="Update">
					            </div>
					        </div>
					    </form>
					</div>
				</div>
			</div>
		</div>
	</section>-->
@endsection

resources/views/admin/users/user.blade.php
@extends('../admin.layout.master')
@section('title', 'Laravel-Crud')
@section('content')
	<section class="main_section">
		@if(session()->has('message'))
		    <div class="alert alert-success">
		        {{ session()->get('message') }}
		    </div>
		@endif 
    	<div class="col-xl-12">
			<div class="card mt-4">
				<div class="card-header">
		    		<div class="top_bar">
						<div class="left">
							<form action="{{ route('user.index') }}" method="GET" role="search">
								<input type="text" class="form-control" placeholder="Enter Name" name="name" value="{{ Request::input('name') }}">
								<input type="text" class="form-control" placeholder="Enter Email" name="email" value="{{ Request::input('email') }}">
								<div class="input-group">
									&nbsp;
									<input type="submit" value="Search" class="btn btn-info">
									&nbsp;
									<a href="{{ route('user.index') }}" class="btn btn-success">Reset</a>
								</div>
							</form>
						</div>
						<div class="right">
							<a href="{{ route('user.create') }}" class="btn btn-info">Add User</a>
						</div>
		    		</div>
				</div>
				<div class="card-body">
		    		<div class="table-responsive">
						<table class="table table-hover">
							<thead>
								<tr>
									<th>@sortablelink('id', 'ID')</th>
									<th>@sortablelink('name', 'Name')</th>
									<th>@sortablelink('email', 'Email')</th>
									<th>Image</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								@if(count($users) > 0)
									@foreach ($users as $user)
										<tr>
											<td>{{ $user->id }}</td>
											<td>{{ $user->name }}</td>
											<td>{{ $user->email }}</td>
											<td>
												<img src="{{ asset('images').'/' .$user->image }}" alt="..." height="30" width="30" />
											</td>
											<td>
												<a href="{{ route('user.edit', ['id' => $user->id]) }}" class="btn btn-info">
													<i class="fa fa-pencil"></i>
												</a>
												<a href="{{ route('user.view', ['id' => $user->id]) }}" class="btn btn-primary">
													<i class="fa fa-eye"></i>
												</a>
												<form method="POST" action="{{ route('user.delete', ['id' => $user->id]) }}">
												    {{ csrf_field() }}
												    {{ method_field('DELETE') }}
												    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i></button>
												</form>
											</td>
										</tr>
									@endforeach
								@else
									<tr>
										<td colspan="5">{{ 'No Record Found ! Try Again!!' }}</td>
									</tr>
								@endif
							</tbody>
						</table> 
						{!! $users->appends(request()->except('page'))->render() !!}
					</div>
				</div>
			</div>
    	</div>
	</section>
@endsection