routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
    |----------Frontend Login Route Start----------|
*/
    Route::get('/frontendlogin', 'Frontend\LoginController@showLoginForm');
    Route::post('/frontendlogin', 'Frontend\LoginController@login')->name('frontendlogin');
    Route::post('/frontendlogout', 'Frontend\LoginController@logout')->name('frontendlogout');
/*
    |----------Frontend Login Route Start----------|
 */
/*-----------------Portfolio Route Start-----------------*/
    Route::get('/portfolio/{slug}', 'Frontend\frontendController@home');
    /*Route::get('/about-us', 'Frontend\frontendController@about');
    Route::get('/services', 'Frontend\frontendController@services');
    Route::get('/team', 'Frontend\frontendController@team');
    Route::get('/contact-us', 'Frontend\frontendController@contactUs');*/
/*-----------------Portfolio Route End-----------------*/

Route::get('/', 'Frontend\frontendController@index');
Route::get('/post/{id}', 'Frontend\frontendController@postDetail')->name('postdetail');
Route::get('/comment', 'Admin\CommentController@index')->name('comment.index');
Route::post('/comment/', 'Admin\CommentController@store')->name('comment.store');
Route::get('/comment/edit/{id}', 'Admin\CommentController@edit')->name('comments.edit');
Route::put('/{id}', 'Admin\CommentController@update')->name('comments.update');
Route::delete('/delete/{id}', 'Admin\CommentController@destroy')->name('comments.delete');



Route::prefix('users')->name('user.')->group(function () {
	Route::get('/', 'Admin\UsersController@index')->name('index');
    Route::get('/add', 'Admin\UsersController@create')->name('create');
    Route::post('/', 'Admin\UsersController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\UsersController@edit')->name('edit');
    Route::put('/{id}', 'Admin\UsersController@update')->name('update');
    Route::get('/view/{id}', 'Admin\UsersController@show')->name('view');
    Route::delete('/delete/{id}','Admin\UsersController@destroy')->name('delete');
});

Route::prefix('posts')->name('posts.')->group(function () {
    Route::get('/', 'Admin\PostController@index')->name('index');
    Route::get('/addpost', 'Admin\PostController@create')->name('create');
    Route::post('/', 'Admin\PostController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\PostController@edit')->name('edit');
    Route::put('/{id}', 'Admin\PostController@update')->name('update');
    Route::get('/view/{id}', 'Admin\PostController@show')->name('view');
    Route::delete('/delete/{id}','Admin\PostController@destroy')->name('delete');

        Route::prefix('image')->name('image.')->group(function () {
            Route::get('/{id}', 'Admin\ImageController@index')->name('listing');
            Route::post('/{id}', 'Admin\ImageController@store')->name('save');
            Route::delete('/delete/{id}', 'Admin\ImageController@destroy')->name('delete');
            Route::get('/edit/{id}', 'Admin\ImageController@edit')->name('edit');
            Route::put('/{id}', 'Admin\ImageController@update')->name('update');
        });
});
Route::prefix('pages')->name('pages.')->group(function (){
    Route::get('/', 'Admin\PagesController@index')->name('index');
    Route::get('/create', 'Admin\PagesController@create')->name('create');
    Route::post('/', 'Admin\PagesController@store')->name('store');
    Route::get('/edit/{id}', 'Admin\PagesController@edit')->name('edit');
    Route::put('/{id}', 'Admin\PagesController@update')->name('update');
    Route::get('/view{id}', 'Admin\PagesController@show')->name('view');
    Route::delete('/delete/{id}','Admin\PagesController@destroy')->name('delete');
});

Route::prefix('menus')->name('menus.')->group(function (){
    Route::get('/', 'Admin\MenuController@index')->name('index');
    Route::get('/create', 'Admin\MenuController@create')->name('create');
    Route::post('/', 'Admin\MenuController@store')->name('store');
    Route::get('edit/{id}', 'Admin\MenuController@edit')->name('edit');
    Route::put('/{id}', 'Admin\MenuController@update')->name('update');
    Route::delete('/delete/{id}', 'Admin\MenuController@destroy')->name('delete');
    /*Route::get('/', 'Admin\SubmenuController@index')->name('index');
    Route::get('/create', 'Admin\SubmenuController@create')->name('create');
    Route::post('/', 'Admin\SubmenuController@store')->name('store');
    Route::get('edit/{id}', 'Admin\SubmenuController@edit')->name('edit');
    Route::put('/{id}', 'Admin\SubmenuController@update')->name('update');
    Route::delete('/delete/{id}', 'Admin\SubmenuController@destroy')->name('delete');*/
});     


Route::get('/login', 'Admin\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Admin\LoginController@login');
Route::post('/logout', 'Admin\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', 'Admin\DashboardController@index');
});

Route::get('/password/reset', 'Admin\ForgotPasswordController@showForm')->name('password.request');
Route::post('password/email', 'Admin\ForgotPasswordController@sendEmail')->name('password.email');
Route::get('password/reset/{token}', 'Admin\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Admin\ResetPasswordController@resetPassword')->name('password.update');

/*Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');*/

resources/views/admin/layout/master.blade.php
<html>
	<head>
		<meta name="csrf-token" content="{{ csrf_token() }}">
		<title>@yield('title')</title>
		<link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
		<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
		<link rel="stylesheet" type="text/css" href="{{ asset('css/adminStyle.css') }}">
		<script src="{{ asset('js/app.js') }}" defer></script>
		<script src="{{ asset('ckeditor/ckeditor.js') }}"></script>
	</head>
	<body>
		<section class="dashboard_section">
			<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
			  	<a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Company name</a>
				<ul class="navbar-nav px-3">
					<li class="nav-item text-nowrap">
						<a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();">
						    Logout
						</a> 
						<form id="frm-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
						    {{ csrf_field() }}
						</form>
					</li>
				</ul>
			</nav>
			<div class="container-fluid">
				<div class="row">
					<nav class="col-md-2 d-none d-md-block bg-light sidebar">
						<div class="sidebar-sticky">
							<ul class="nav flex-column">
								<li class="nav-item">
									<a class="nav-link active" href="{{ url('dashboard') }}">
										<i class="fa fa-tachometer" aria-hidden="true"></i>
										Dashboard
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{ route('user.index') }}">
										<i class="fa fa-folder-o" aria-hidden="true"></i>
										Users
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{ route('posts.index')}}">
										<i class="fa fa-folder-o" aria-hidden="true"></i>
										Posts
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{ route('comment.index')}}">
										<i class="fa fa-folder-o" aria-hidden="true"></i>
										Comments
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{ route('pages.index')}}">
										<i class="fa fa-folder-o" aria-hidden="true"></i>
										Pages
									</a>
								</li>
								<li class="nav-item">
									<a class="nav-link" href="{{ route('menus.index') }}">
										<i class="fa fa-folder-o" aria-hidden="true"></i>
										Menus
									</a>
								</li>
							</ul>
						</div>
					</nav>
					<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
						@yield('content')
					</main>
				</div>
			</div>
		</section>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
		<script>
		   var konten = document.getElementById("content");
		   CKEDITOR.replace(konten,{
		    	language:'en-gb'
		   });
		   CKEDITOR.config.allowedContent = true;
		</script>
		<script type="text/javascript">
			function show_page(){
			  document.getElementById('page').style.display ='block';
			  document.getElementById('url').style.display ='none';
			}
			function show_url(){
			  document.getElementById('url').style.display = 'block';
			  document.getElementById('page').style.display ='none';
			}
		</script>
	</body>
</html>